title:             HomeBrewedSec Blog
email:             huddon@homebrewedsec.com
description:       Brew Beer. Secure Things.
author:            HomeBrewedSec
baseurl:           ""
url:               "http://HomeBrewedSec.com"
permalink:         pretty

# Social Profiles
twitter_username:  HomeBrewedSec
github_username:   
facebook_username: 

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-twitter-plugin
